name: Build & deploy

on:
  push:
    branches:
      - main
    paths:
      - website-astro/**      
  pull_request:
    branches:
      - main      
    paths:
      - website-astro/**

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website-astro    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
    - name: Install dependencies
      run: yarn --frozen-lockfile      
    - name: Building Astro Website
      run: yarn build
    - name: Deploying
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 sync --delete --acl public-read website-astro/dist/ s3://${{ secrets.AWS_S3_BUCKET }}/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
