name: Build & deploy

on:
  push:
    branches:
      - main
    paths:
      - website-astro/**      
  pull_request:
    branches:
      - main      
    paths:
      - website-astro/**

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website-astro    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
    - name: Install dependencies
      run: yarn --frozen-lockfile      
    - name: Building Astro Website
      run: yarn build
    - name: Deploying
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --no-follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'website-astro/dist/'
